name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: matt-riley/matt-riley-ci/.github/workflows/node-ci.yml@2bfd14c931b9ae3c03501fedbfa12303b2f5204e # main
    with:
      package-manager: pnpm
      run-lint: true
      run-test: true
      run-build: true
