name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: matt-riley/matt-riley-ci/.github/workflows/node-ci.yml@835c12d10fac013404b8fc0f6210fd5ccec2e332 # main
    with:
      package-manager: pnpm
      run-lint: true
      run-test: true
      run-build: true
